language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
install:
- pip install nose coveralls
- pip install -e .
script:
- nosetests -q --with-doctest --with-coverage
after_success:
- coveralls
